spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.60:3306/guestroom?serverTimezone=GMT&characterEncoding=utf-8
    username: root
    password: 123456@abcABC
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
server:
  port: 80
  tomcat:
    accept-count: 200
    max-threads: 200
logging:
  path: /usr/java/logger